modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/perxenic-studios/saturatedsands/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"


displayURL="https://www.perxenic.dev/saturatedsands"
logoFile="assets/saturatedsands/icon.png"

authors="Auseawesome"
description='''
Adds more colored variations and patterns to the decorative blocks from Mirage!
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mirage"
    type="required"
    versionRange="[${mirage_version},)"
    ordering="NONE"
    side="BOTH"
